### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by 2922832737C** [theailifestyle/AssistantsAPI#1]
![image](https://github.com/theailifestyle/AssistantsAPI/assets/115255509/ae7c2f9c-f95f-4b9f-ac76-c14c09ce1881)

**Comment by stephencurry300728** [comment]
import os
os.environ["http_proxy"] = "http://localhost:7890"   # clash默认用的7890作为port
os.environ["https_proxy"] = "http://localhost:7890" # clash默认用的7890作为port
这个应该能解决你的问题

**Comment by stephencurry300728** [comment]
`import os
os.environ["http_proxy"] = "http://localhost:7890/" # clash默认用的7890作为port
os.environ["https_proxy"] = "http://localhost:7890/" # clash默认用的7890作为port`
这个应该能解决你的问题

**Comment by stephencurry300728** [comment]
import os
# 设置代理避免报错openai.error.APIConnectionError
os.environ["http_proxy"] = "http://localhost:7890" # clash默认用7890作为port
os.environ["https_proxy"] = "http://localhost:7890"
这个应该能解决你的问题
